// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBITc9W8I6CX_XNMc2JQWHvrtFbWV1YMU4',
    appId: '1:761481387472:web:42cc307bda167e9eee6dd5',
    messagingSenderId: '761481387472',
    projectId: 'flight-app-ad69e',
    authDomain: 'flight-app-ad69e.firebaseapp.com',
    storageBucket: 'flight-app-ad69e.firebasestorage.app',
    measurementId: 'G-CXNGV9WYJ5',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0-E2A0xFMh71STjlsac1lvOFtI__3qX8',
    appId: '1:761481387472:ios:60e1acacb4ab1476ee6dd5',
    messagingSenderId: '761481387472',
    projectId: 'flight-app-ad69e',
    storageBucket: 'flight-app-ad69e.firebasestorage.app',
    iosClientId: '761481387472-k6n9pt346ftfh8lm4cfpjfd9gvjm98h6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flighteasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0-E2A0xFMh71STjlsac1lvOFtI__3qX8',
    appId: '1:761481387472:ios:60e1acacb4ab1476ee6dd5',
    messagingSenderId: '761481387472',
    projectId: 'flight-app-ad69e',
    storageBucket: 'flight-app-ad69e.firebasestorage.app',
    iosClientId: '761481387472-k6n9pt346ftfh8lm4cfpjfd9gvjm98h6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flighteasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBITc9W8I6CX_XNMc2JQWHvrtFbWV1YMU4',
    appId: '1:761481387472:web:e9253dbe4fbbacc3ee6dd5',
    messagingSenderId: '761481387472',
    projectId: 'flight-app-ad69e',
    authDomain: 'flight-app-ad69e.firebaseapp.com',
    storageBucket: 'flight-app-ad69e.firebasestorage.app',
    measurementId: 'G-DXRYSJLJNW',
  );

}